version: '3.3'

services:
  nginx:
    build: ./nginx
    restart: always
    volumes:
      - "./nginx/default.conf:/etc/nginx/conf.d/default.conf"
      - "./..:/var/www/magento2"
    ports:
      - "80:80"
    depends_on:
      - php
      - mysql

  php:
    build: ./php
    restart: always
    volumes:
      - "./..:/var/www/magento2"
      - "./php/php.ini:/usr/local/etc/php/conf.d/custom.ini"
    environment:
      - "PHP_IDE_CONFIG=serverName=PHPSTORM_DOCKER"
    env_file: .env

  mysql:
    build: ./mysql
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    restart: always
    env_file: .env
